server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8

#exchange-rate-api:
#  base-url: https://v6.exchangerate-api.com/v6/
#  api-key: random-api-key
#twilio-api:
#  base-url: https://api.twilio.com/2010-04-01
#  account-sid: random-account-sid

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
#    open-in-view: true
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
